name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Run Django Api Test
        run: |
          pip3 install --user pipenv

      - name: Install Dependencies
        run: |
          pipenv install --dev
      - name: list installed dependencies
        run: |
          pipenv run pip freeze
      - name: change to project directory
        run: |
          cd backend
          ls
      - name: setup database
        run: |
          pipenv run python3 manage.py makemigrations account
         
      - name: migrate database
        run: |
          pipenv run python3 manage.py migrate

      - name: run tests
        run: |
         pipenv run python3 manage.py test
