name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Run Django Api Test
        run: |
          pip3 install --user pipenv
          pipenv install
          cd backend
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py test
